extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const MacroObject castle_courtyard_area_1_macro_objs[];
extern u8 castle_courtyard_dl_cs_lawn03_alb_ci8[];
extern u8 castle_courtyard_dl_cs_lawn03_alb_pal_rgba16[];
extern Vtx castle_courtyard_dl_Plane_mesh_layer_1_vtx_0[537];
extern Gfx castle_courtyard_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_courtyard_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_courtyard_dl_f3dlite_material_002[];
extern Gfx castle_courtyard_dl_Plane_mesh_layer_1_with_revert[];
