extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern u8 sl_dl_cs_lawn03_alb_ci8[];
extern u8 sl_dl_cs_lawn03_alb_pal_rgba16[];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_0[537];
extern Gfx sl_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_sl_dl_f3dlite_material_002[];
extern Gfx mat_revert_sl_dl_f3dlite_material_002[];
extern Gfx sl_dl_Plane_mesh_layer_1_with_revert[];
