extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern u8 bits_dl_cs_lawn03_alb_ci8[];
extern u8 bits_dl_cs_lawn03_alb_pal_rgba16[];
extern Vtx bits_dl_Plane_mesh_layer_1_vtx_0[537];
extern Gfx bits_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bits_dl_f3dlite_material_002[];
extern Gfx mat_revert_bits_dl_f3dlite_material_002[];
extern Gfx bits_dl_Plane_mesh_layer_1_with_revert[];
