extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_macro_objs[];
extern u8 bitdw_dl_cs_lawn03_alb_ci8[];
extern u8 bitdw_dl_cs_lawn03_alb_pal_rgba16[];
extern Vtx bitdw_dl_Plane_mesh_layer_1_vtx_0[537];
extern Gfx bitdw_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bitdw_dl_f3dlite_material_002[];
extern Gfx mat_revert_bitdw_dl_f3dlite_material_002[];
extern Gfx bitdw_dl_Plane_mesh_layer_1_with_revert[];
